### PR TITLE
Fix envelope list selection

### PR DESCRIPTION
**Pull request by st3iny**
Fixes not being able to select envelopes from the list. This is a regression introduced by #4345.

Both `areAllSelectedRead` and `areAllSelectedFavorite` are computed properties so they can't be called.

Error message:
```
[Vue warn]: Error in render: "TypeError: _vm.areAllSelectedRead is not a function"

found in

---> <EnvelopeList> at src/components/EnvelopeList.vue
       <Mailbox> at src/components/Mailbox.vue
         <AppContentList>
           <AppContent>
             <MailboxThread> at src/components/MailboxThread.vue
               <Content>
                 <Home> at src/views/Home.vue
                   <App> at src/App.vue
                     <Root>
```

### CODE REVIEW

**Comment by st3iny** [comment]
Found while testing https://github.com/nextcloud/mail/pull/4574

**Review by GretaD — APPROVED** [review]
